# Generated by Django 3.1 on 2020-08-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_libbookacquired'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LibBookAcquired',
        ),
    ]
