# Generated by Django 3.1 on 2020-09-27 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0013_auto_20200927_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='man-300x300_DJNAjxd.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='libuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
