# Generated by Django 3.1 on 2020-10-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200927_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='libbook',
            name='cover_pic',
            field=models.ImageField(blank=True, default='book-default.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='libuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='vlbuser.png', null=True, upload_to=''),
        ),
    ]
